// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmi-7SWp_abJnlF1i7ljeq9nFSGvtvZI',
    appId: '1:940804112641:web:2cca18c4129267041d9b00',
    messagingSenderId: '940804112641',
    projectId: 'gymbuddy-b4e20',
    authDomain: 'gymbuddy-b4e20.firebaseapp.com',
    storageBucket: 'gymbuddy-b4e20.appspot.com',
    measurementId: 'G-MBL31251F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw07k4cdY5tso33lh9i4guaqzvr62Czog',
    appId: '1:940804112641:android:d7f3e67d6338662d1d9b00',
    messagingSenderId: '940804112641',
    projectId: 'gymbuddy-b4e20',
    storageBucket: 'gymbuddy-b4e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWuA1xrg0-ThKCiOa244f65nYUXE9tuSc',
    appId: '1:940804112641:ios:e82c5e167b4112f51d9b00',
    messagingSenderId: '940804112641',
    projectId: 'gymbuddy-b4e20',
    storageBucket: 'gymbuddy-b4e20.appspot.com',
    iosClientId: '940804112641-5qnvjv38avc7f4q7efchuklti82qi2se.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWuA1xrg0-ThKCiOa244f65nYUXE9tuSc',
    appId: '1:940804112641:ios:157e4b1744a6c0481d9b00',
    messagingSenderId: '940804112641',
    projectId: 'gymbuddy-b4e20',
    storageBucket: 'gymbuddy-b4e20.appspot.com',
    iosClientId: '940804112641-4f7umuaohdtkn511io45sf1b4aeiocuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymbuddy.RunnerTests',
  );
}
