openapi: 3.0.1
info:
  title: Workout-runner API
  description: GymBuddy workout runner backend API
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /workout/runner:
    get:
      tags:
        - runner-controller
      operationId: getRecords
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - name: workoutId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: sessionId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StepRecordResponse'
    post:
      tags:
        - runner-controller
      operationId: recordStep
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRecordDto'
        required: true
      responses:
        '200':
          description: OK
components:
  schemas:
    PostRecordDto:
      type: object
      properties:
        workoutId:
          type: integer
          format: int64
        stepId:
          type: integer
          format: int64
        sessionId:
          type: string
        duration:
          type: number
    StepRecordResponse:
      type: object
      properties:
        stepId:
          type: integer
          format: int64
        completedAt:
          type: string
          format: date-time
        duration:
          type: number
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
